apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paw-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/beetlejuice96/TP-Integrador-PAW.git
    targetRevision: HEAD
    path: Kubernetes/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  #syncPolicy:
  #  automated:
  #    prune: false
  #    selfHeal: false