name: Build App Container & Push to Dockerhub

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Build and push app image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_NAME: "MechanicSheep"
          envkey_APP_ENV: "local"
          envkey_APP_KEY: ""
          envkey_APP_DEBUG: false
          envkey_APP_URL: "http://develop.mechanicsheep.com.ar"
          envkey_DB_CONNECTION: mysql
          envkey_DB_HOST: mechanicsheep-db
          envkey_DB_PORT: 3306
          envkey_DB_DATABASE: MechanicSheep
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_ID_CLIENT_GOOGLE: ${{ secrets.ID_CLIENT_GOOGLE }}
          envkey_SECRET_GOOGLE: ${{ secrets.SECRET_GOOGLE }}
          envkey_LOG_SLACK_WEBHOOK_URL: ${{ secrets.LOG_SLACK_WEBHOOK_URL }}
          envkey_LOG_LEVEL: "debug"
          envkey_LOG_CHANNEL: "stack"
          envkey_GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          envkey_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          envkey_GITHUB_REPO: ${{ secrets.GITHUB_REPO }}

          file_name: .env

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dilanbernabe/mechanicsheep:latest
