name: Build App Container & Push to Dockerhub

on:
  push:
    paths:
    - 'SourceCode/**'
    
jobs:
  build:
    name: Build and push app image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_NAME: "MechanicSheep"
          envkey_APP_ENV: "local"
          envkey_APP_KEY: ""
          envkey_APP_DEBUG: false
          envkey_APP_URL: "http://develop.mechanicsheep.com.ar"
          envkey_DB_CONNECTION: mysql
          envkey_DB_HOST: mechanicsheep-db
          envkey_DB_PORT: 3306
          envkey_DB_DATABASE: MechanicSheep
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.ID_CLIENT_GOOGLE }}
          envkey_GOOGLE_SECRET: ${{ secrets.SECRET_GOOGLE }}
          envkey_GOOGLE_REDIRECT_URI: "https://develop.mechanicsheep.com.ar"
          envkey_LOG_SLACK_WEBHOOK_URL: ${{ secrets.LOG_SLACK_WEBHOOK_URL }}
          envkey_LOG_LEVEL: "debug"
          envkey_LOG_CHANNEL: "stack"
          envkey_GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          envkey_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          envkey_GITHUB_REPO: ${{ secrets.GH_REPO }}

          file_name: .env

      - name: ls for debug
        run: ls -la

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dilanbernabe/mechanicsheep:latest, dilanbernabe/mechanicsheep:${{ github.sha }}
    
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        run: |
        cd kustomize/
        kustomize edit set image mechanicsheep-image=dilanbernabe/mechanicsheep:$GITHUB_SHA
        cat kustomization.yaml

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: './kustomize/'
          kustomize_comment: true
          kustomize_output_file: "Kubernetes/01-app-deployment.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          path: './Kubernetes'
            
